name: DanielFarmer.ca
favicon: null
layout_spectrum: 0.8550367376301438
typography_spectrum: 0.09364953683689237
title: Daniel Farmer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3803893697913736
  lightness: 0.825934368185699
  saturation: 0.2835466102696955
  rhythmicContrast: 0.3351209801621735
purpose: []
