typography_spectrum: 0.2638006389606744
color:
  brandColors:
    - '#962D3E'
    - '#343642'
    - '#979C9C'
    - '#F2EBC7'
    - '#348899'
  brandStrength: 0.3222284917719662
  lightness: 0.6964545946102589
  saturation: 0.9316036959644407
  rhythmicContrast: 0.8467223662883043
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4266867411788553
analytics:
  google: UA-5100962-4
  facebook: null
  twitter: null
name: DanielFarmer.ca
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Linkedin Profile
    url: 'https://ca.linkedin.com/in/paradigmthinking'
    type: external
favicon: null
title: Daniel Farmer
description: '♠ Exceeding objectives by challenging status quo ♠ '
purpose: []
