name: DanielFarmer.ca
favicon: null
layout_spectrum: 0.24427
typography_spectrum: 0.74729
title: Daniel Farmer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-5100962-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#21221f'
    - '#87929d'
    - '#bdc8d1'
    - '#d9aa85'
    - '#69747e'
  brandStrength: 0.8125
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
