typography_spectrum: 0.74729
color:
  brandColors:
    - '#21221f'
    - '#87929d'
    - '#bdc8d1'
    - '#d9aa85'
    - '#69747e'
  brandStrength: 0.8125
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24427
analytics:
  google: UA-5100962-4
  facebook: null
  twitter: null
name: DanielFarmer.ca
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Linkedin Profile
    url: 'https://ca.linkedin.com/in/paradigmthinking'
    type: external
favicon: null
title: Daniel Farmer
description: '♠ Exceeding objectives by challenging status quo ♠ '
purpose: []
